import type { Metadata } from "next";
import styles from "./page.module.css";
import { Inter } from "next/font/google";
import Breadcrumb from "./products/Components/Breadcrumb";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "React server components",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.headerNav} >
          <Breadcrumb></Breadcrumb>
        </div>
        {children}
      </body>
    </html>
  );
}
